--- #YAML:1.0
name: Test-Exception
version: 0.21
author:
  - Adrian Howard <adrianh@quietstars.com>
abstract: Test exception based code
license: perl
generated_by: Module::Build version 0.261, without YAML.pm
