--- #YAML:1.0
name:               Test-Exception
version:            0.27_03
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Sub::Uplevel:         0.18
    Test::Builder:        0.7
    Test::Builder::Tester:  1.07
    Test::Harness:        2.03
    Test::More:           0.7
    Test::Simple:         0.7
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
